name: Continuous Integration

on:  # Define here when your project will be tested
  push:               # only those branchs with those tags are tested
    branches:
      - main
      - dev_packing
    tags:
      - '*'
  pull_request:       # all pull-requests will be tested
  workflow_dispatch:  # this allows you to "manually" launch the workflow

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest

    # Here we will define the testing "matrix"
    # -- It can be composed of whatever your matrix may be,
    # -- including OS variations (e.g. windows, macos, etc).
    # -- The executor will combine all possible values together
    strategy:
      fail-fast: false  # avoids cancelled builds if the other fails
      matrix:
        python-version: ["3.8", "3.9"]

    # Here we define the steps to be undertaken for every test
    # -- Each step does one action.  Code for the action sits in
    # -- another github project (key "uses").  This way, actions
    # -- can be programmed for any purpose.
    steps:

      # Action provided by GitHub to checkout code
      - name: Check out repository code
        uses: actions/checkout@v2
        
      # Prepares the Python environment
      - name: Prepare Python
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      # Install build requirement lib
      - name: Install Python lib
        shell: bash -l {0}
        run: |
          pip install .
          pip install -r build-requirements.txt  #only required for CI tests

      # Run test
      - name: Run test
        shell: bash -l {0}
        run: |
          pytest -sv --cov=.

      # Upload coverage
      - name: Upload coverage to coveralls.io
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          coveralls --service=github

      # Build documentation for the GitHub pages
      - name: Build documentation
        if: ${{ matrix.python-version == '3.9' && startsWith(github.ref, 'refs/tags')}}  #builds only one variant
        shell: bash -l {0}
        run: |
          sphinx-build doc/source doc/build/html  #generates html version of docs
          touch doc/build/html/.nojekyll  #pages to be deployed are NOT a Jekyll site
      
      - name: Deploy documentation to GitHub Pages
        if: ${{ matrix.python-version == '3.9' && startsWith(github.ref, 'refs/tags')}}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: doc/build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build packing for PyPI
      - name: Build PyPI
        if: ${{ matrix.python-version == '3.9' && startsWith(github.ref, 'refs/tags')}}  #builds only one variant
        shell: bash -l {0}
        run: |
          python3 setup.py sdist

      - name: Deploy packing for TestPyPI
        if: ${{ matrix.python-version == '3.9' && startsWith(github.ref, 'refs/tags')}}
        uses: pypa/gh-action-pypi-publish@master
        with:
           verbose: true
           password: ${{ secrets.TEST_PYPI_API_TOKEN }}
           repository_url: https://test.pypi.org/legacy/

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
